const questions = [
  { id: 1, text: "We enjoy spending time together." },
  { id: 2, text: "We communicate openly and honestly." },
  { id: 3, text: "We resolve conflicts respectfully." },
  { id: 4, text: "We feel emotionally connected." },
  { id: 5, text: "We support each other’s dreams." },
  { id: 6, text: "We trust each other completely." },
  { id: 7, text: "We feel appreciated by each other." },
  { id: 8, text: "We handle stress well together." },
  { id: 9, text: "We share similar values." },
  { id: 10, text: "We feel comfortable being ourselves." },
  { id: 11, text: "We have a healthy physical relationship." },
  { id: 12, text: "We manage finances well together." },
  { id: 13, text: "We respect each other’s boundaries." },
  { id: 14, text: "We enjoy making plans together." },
  { id: 15, text: "We feel like a team." },
  { id: 16, text: "We talk about our future together." },
  { id: 17, text: "We feel emotionally safe with each other." },
  { id: 18, text: "We listen without interrupting." },
  { id: 19, text: "We give each other space when needed." },
  { id: 20, text: "We celebrate each other’s achievements." },
  { id: 21, text: "We are affectionate with each other." },
  { id: 22, text: "We feel connected even when apart." },
  { id: 23, text: "We handle disagreements calmly." },
  { id: 24, text: "We have shared goals." },
  { id: 25, text: "We support each other’s mental health." },
  { id: 26, text: "We feel loved and valued." },
  { id: 27, text: "We make time for each other." },
  { id: 28, text: "We talk about money openly." },
  { id: 29, text: "We share household responsibilities." },
  { id: 30, text: "We respect each other’s opinions." },
  { id: 31, text: "We enjoy each other’s company." },
  { id: 32, text: "We feel respected in our relationship." },
  { id: 33, text: "We support each other’s family relationships." },
  { id: 34, text: "We have fun together." },
  { id: 35, text: "We communicate our needs clearly." },
  { id: 36, text: "We feel emotionally supported." },
  { id: 37, text: "We handle stress in a healthy way." },
  { id: 38, text: "We make decisions together." },
  { id: 39, text: "We trust each other’s judgement." },
  { id: 40, text: "We are honest with each other." },
  { id: 41, text: "We feel emotionally stable together." },
  { id: 42, text: "We respect each other’s privacy." },
  { id: 43, text: "We share similar life goals." },
  { id: 44, text: "We feel safe discussing difficult topics." },
  { id: 45, text: "We support each other’s personal growth." },
  { id: 46, text: "We feel emotionally close." },
  { id: 47, text: "We make time for romance." },
  { id: 48, text: "We communicate in a loving way." },
  { id: 49, text: "We respect each other’s boundaries." },
  { id: 50, text: "We feel supported during hard times." },
  { id: 51, text: "We feel like we can be ourselves." },
  { id: 52, text: "We handle conflicts respectfully." },
  { id: 53, text: "We feel grateful for each other." },
  { id: 54, text: "We share responsibilities fairly." },
  { id: 55, text: "We enjoy talking together." },
  { id: 56, text: "We feel emotionally connected." },
  { id: 57, text: "We support each other’s goals." },
  { id: 58, text: "We feel secure in our relationship." },
  { id: 59, text: "We communicate openly about
